[project]
name = "carvera-controller-community"
description = "Community developed controller for the Carvera CNC"
version = "0.0.0"
license = "GPL-2.0"
readme = "README.md"
requires-python = "<3.14,>=3.9"
dependencies = [
    "Kivy >=2.3.1,<3.0.0",
    "pyserial >=3.5,<4.0.0",
    "pyquicklz >=1.4.1,<2.0.0",
    "hid >=1.0.7,<2.0.0"
]

[tool.hatch.build.targets.wheel]
packages = ["carveracontroller"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
carvera-controller-community = "carveracontroller.__main__:main"
