[project]
name = "carvera-controller-community"
description = "Community developed controller for the Carvera CNC"
version = "0.0.0"
license = "GPL-2.0"
readme = "README.md"
requires-python = "<3.14,>=3.9"
dependencies = [
    "Kivy >=2.3.1,<3.0.0",
    "pyserial >=3.5,<4.0.0",
    "pyquicklz >=1.4.1,<2.0.0",
    "hid >=1.0.7,<2.0.0"
]

[tool.hatch.build.targets.wheel]
packages = ["carveracontroller"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
carvera-controller-community = "carveracontroller.__main__:main"
carvera-controller-whb04dbg = "carveracontroller.addons.pendant.whb04:__main__"

[tool.uv.extra-build-dependencies]
altgraph = [ "setuptools" ]
buildozer = [ "setuptools" ]
carvera-controller-community = [ "hatchling" ]
certifi = [ "setuptools" ]
charset-normalizer = [ "setuptools" ]
distlib = [ "setuptools" ]
docutils = [ "flit-core" ]
filelock = [
    "hatchling",
    "hatch-vcs"
]
filetype = [ "setuptools" ]
hid = [ "setuptools" ]
idna = [ "flit-core" ]
markupsafe = [ "setuptools" ]
packaging = [ "flit-core" ]
platformdirs = [
    "hatchling",
    "hatch-vcs"
]
pygments = [ "hatchling" ]
pyquicklz = [
    "setuptools",
    "cython"
]
pyserial = [ "setuptools" ]
pyyaml = [ "setuptools" ]
ruamel-yaml = [ "setuptools" ]
ruamel-yaml-clib = [ "setuptools" ]
toml = [ "setuptools" ]
ptyprocess = [ "flit-core" ]
jinja2 = [ "flit-core" ]
pexpect = [ "setuptools" ]
pyinstaller = [
    "hatchling"
]
pyinstaller-versionfile = [ "poetry-core" ]
sh = [ "poetry-core" ]
typing-extensions = [ "flit-core" ]
urllib3 = [
    "hatchling",
    "hatch-vcs"
]
virtualenv = [
    "hatchling",
    "hatch-vcs"
]
requests = [ "setuptools" ]
kivy = [
    "setuptools",
    "cython"
]
